all:
  hosts:
    node1:
      ansible_host: 3.239.195.70
    node2:
      ansible_host: 98.82.19.90
    node3:
      ansible_host: 44.198.180.146
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/key/swarmlab_clone
    overlay_network: swarmlab_net
    docker_login_user: emanuelswarmlab
    docker_stack: swarmlab
    docker_login_pass: !vault |
          $ANSIBLE_VAULT;1.2;AES256;personal
          64656331653562656533633364613633323236353133623832343431613839383439626164636337
          6264346465373863306661616561663562646163383863640a313635376139663433333436376364
          63613531636166626335353836663364393334353765316361663133333362323730643966353330
          6362383664343835310a313737386438303538326562313935336132363066336430386238643338
          6131
    docker_login_token: !vault |
              $ANSIBLE_VAULT;1.2;AES256;personal
              39336161333665666130343066626332643434343661646537366230346562633464316237313237
              3235363037356336373730343737313564653764666264330a313762643466643263333531333634
              62323937303065613233366234303264393638353134343736383939373763383338343764353136
              3631323532636365380a316232633731323263323763303632343035343265363431636663313431
              63623066303837626135383138616333333839636236346239326665633065316234303234306165
              6233656262396436393938336137613062356337376233663431
    patroni_version: v4.0.5
    patroni_image: patroni-citus
