networks:
  pg:

volumes:
  postgres_16_data:

services:
  postgres_16:
    container_name: postgres_16
    build:
      context: ./docker
    #   # dockerfile: ./docker/Dockerfile
    image: conductor/pg
    # image: postgres:16
    environment:
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: password
      POSTGRES_DB: conductor
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15432:5432"
    volumes:
      - ./postgres_16_data:/var/lib/postgresql/data
      - ./entrypoint:/docker-entrypoint-initdb.d
    networks:
      - pg
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=4
               -c max_wal_senders=4
               -c listen_addresses='*'
               -c shared_preload_libraries='pg_cron,pg_partman_bgw'


